name: Embedded Postgres
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: go
        uses: actions/checkout@v1
      - name: Set Up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Fetch Dependencies
        run: |
          go get -v -t ./...
      - name: Nancy Vulnerability
        uses: sonatype-nexus-community/nancy-github-action@master
        with:
          target: go.sum
      - name: Test
        run: go test -v -race -cover -covermode=atomic -coverprofile=coverage.out ./...
      - name: Test Examples
        run: |
          pushd examples && \
          go test -v ./... && \
          popd
      - name: Upload Coverage Report
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: GO111MODULE=off go get github.com/mattn/goveralls && $(go env GOPATH)/bin/goveralls -v -coverprofile=coverage.out -service=github
  platform_tests:
    name: Platform tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Platform Tests
        run: |
          cd platform-test
          go get -v -t ./...
          go test -v ./...
