name: Embedded Postgres Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: go
        uses: actions/checkout@v1
      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Fetch Dependencies
        run: go get -v -t ./...
      - name: Test
        run: go test -v ./...
      - name: Test Examples
        run: |
          pushd examples && \
          go test -v ./... && \
          popd
      - name: Build
        run: go build -v .