name: Embedded Postgres Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: go
        uses: actions/checkout@v1
      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Fetch Dependencies
        run: |
          go get -v -t ./...
      - name: Test
        run: go test -v -race -cover -covermode=atomic -coverprofile=coverage.out ./...
      - name: Test Examples
        run: |
          pushd examples && \
          go test -v ./... && \
          popd
      - name: Upload Coverage Report
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: GO111MODULE=off go get github.com/mattn/goveralls && $(go env GOPATH)/bin/goveralls -v -coverprofile=coverage.out -service=github
      - name: Build
        run: go build -v .
